# Generated by Django 5.2.3 on 2025-07-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cloud_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
