# Generated by Django 5.1.4 on 2025-07-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_wallettransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransfer',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
