# Generated by Django 5.1.4 on 2025-01-06 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_business_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='firstname', #Or first_name depending on your model
            new_name='temp_firstname',
        ),
    ]
