# Generated by Django 5.1.4 on 2025-01-06 15:18
from django.db import models
from django.db import migrations
from django.db.models import Count

def populate_first_name(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    duplicate_names = CustomUser.objects.values('temp_firstname').annotate(name_count=Count('temp_firstname')).filter(name_count__gt=1)
    for name_data in duplicate_names:
        first_name = name_data['temp_firstname']
        users_with_name = list(CustomUser.objects.filter(temp_firstname=first_name).order_by('pk'))
        for i, user in enumerate(users_with_name[1:]):
            new_first_name = f"{first_name}_{user.pk}"
            user.first_name = new_first_name
            user.save()
    CustomUser.objects.all().update(first_name=models.F('temp_firstname'))


def reverse_populate_first_name(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    CustomUser.objects.all().update(temp_firstname=models.F('first_name'))

class Migration(migrations.Migration):
    dependencies = [
        ('users', '0008_add_new_firstname'),
    ]

    operations = [
        migrations.RunPython(populate_first_name, reverse_populate_first_name),
    ]