# Generated by Django 5.1.4 on 2025-01-06 15:28

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('users', '0009_populate_new_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=30, default=''),  # Set a default empty string
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='temp_firstname',
        ),
    ]
