# Generated by Django 5.1.4 on 2025-01-08 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customuser_name'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='customuser',
    #         name='username',
    #     ),
    # ]
