# Generated by Django 5.1.4 on 2025-01-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='NIN',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
