# Generated by Django 5.1.4 on 2025-02-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/profile_photo.jpeg', null=True, upload_to='profile_pics/'),
        ),
    ]
