# Generated by Django 5.1.4 on 2025-03-28 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_invoice_invoiceitem_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
