# Generated by Django 5.1.4 on 2025-03-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_payment_amount_payment_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
