# Generated by Django 5.1.4 on 2025-03-13 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_payment_amount_alter_payment_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.products'),
        ),
    ]
