# Generated by Django 5.1.4 on 2025-03-13 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_paymentitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='invoice',
            new_name='invoice_id',
        ),
    ]
