# Generated by Django 5.1.4 on 2025-03-14 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_payment_invoice_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='invoice_id',
            new_name='invoice',
        ),
    ]
