# Generated by Django 5.1.4 on 2025-03-14 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_rename_invoice_id_payment_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='invoice_id',
            new_name='invoice',
        ),
    ]
