# Generated by Django 5.1.4 on 2025-03-29 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_paymentitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.invoice'),
        ),
    ]
