# Generated by Django 5.1.4 on 2025-04-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_payment_grand_total_paymentitem_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
