# Generated by Django 5.1.4 on 2025-04-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_registration', 'New Registration'), ('birthday', 'Birthday'), ('invoice_created', 'Invoice Created'), ('payment_success', 'Payment Success'), ('bonus_product', 'Bonus Product'), ('incentive', 'Incentive')], default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
