# Generated by Django 5.1.4 on 2025-05-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='maintenance_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
